### PR TITLE
fix: add logic to save request button

### LINKED ISSUE #111: save button not working
Hi.

When editing a request, pressing the save button does not work but closing it (switching to another request) or sending a successful request saves it.

Version : docker latest (no version information in "about")

### PR DESCRIPTION
**Pull request by n14s**
This MR implements the logic of the save request button. 

Resolves #111

### CODE REVIEW

File: client/src/pages/dashboard/Dashboard.tsx [hunk 1]
```diff
@@ -344,6 +344,28 @@ function Dashboard() {
     selectCollectionRef.current = selectCollection;
   }, [selectCollection]);
 
+  const saveRequest = useCallback(
```
Comment (jonrosner) [inline client/src/pages/dashboard/Dashboard.tsx:347]: rather than writing this again, pass the `handleSaveRequestClick` defined in `RequestSender` down to `RequestPanel`.

It will be difficult right now to refactor it into the dashboard, as we'll need to handle the case where no collection is selected and this requires a lot of state that's currently in the RequestSender.

So for now I suggest to do it as I described above.
